/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class spade_reporter_LinuxFUSE */

#ifndef _Included_spade_reporter_LinuxFUSE
#define _Included_spade_reporter_LinuxFUSE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     spade_reporter_LinuxFUSE
 * Method:    launchFUSE
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_spade_reporter_LinuxFUSE_launchFUSE
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
